image: python:3.7

before_script:
    - pip3 install python-dateutil psycopg2 mypy flake8 flake8-mutable flake8-annotations flake8-blind-except flake8-comprehensions flake8-executable flake8-fixme flake8_builtins flake8-use-fstring

variables:
    MAKEFLAGS: "-j7 --output-sync=target"
    GIT_SUBMODULE_STRATEGY: recursive

check:
  script:
      - make check
  tags:
      - shared-fi
