image: python:3.7

before_script:
    - pip3 install python-dateutil psycopg2 mypy flake8

variables:
    MAKEFLAGS: "-j7 --output-sync=target"
    GIT_SUBMODULE_STRATEGY: recursive

check:
  script:
      - make check
  tags:
      - shared-fi
