#!/usr/bin/env python3
from __future__ import annotations

import argparse
import enum
import common
import isapi.files
import os
import os.path
import psycopg2  # type: ignore
import re
import smtplib
import typing

from dataclasses import dataclass
from datetime import datetime
from email.message import EmailMessage
from isapi.files import FileMeta
from typing import Optional, TypeVar, Iterable, Dict, List, Tuple, Any
from common import to_utc_strip

τ = TypeVar("τ")


def cmdparser() -> argparse.ArgumentParser:
    return common.cmdparser("Poller for connecting IS submission folders "
                            "to FRAG")


class MultiFile(enum.Enum):
    Disabled = enum.auto()
    Any = enum.auto()
    All = enum.auto()

    @staticmethod
    def parse(raw: str) -> MultiFile:
        raw = raw[0].upper() + raw[1:].lower()
        return MultiFile.__members__[raw]


class Assignment(common.BaseAssignment):
    RE_ANY = re.compile(".*")

    def __init__(self, raw: dict, name: str, config: Config,
                 db: common.DBConnection) -> None:
        super().__init__(raw, name, config, db)
        assert "source" in self.raw
        source = self.raw['source']
        if source.startswith('/'):
            self.sources = [source]
        else:
            assert "sources" in config.raw
            assert source in config.raw["sources"]
            self.sources = config.raw["sources"][source]
        self.name_template: Optional[str] = self.raw.get('name template')
        self.multifile = MultiFile.parse(self.raw.get('multifile', 'disabled'))

    def __str__(self) -> str:
        return self._str(f"sources = {self.sources} "
                         f"template = {self.name_template} "
                         f"multifile = {self.multifile}")

    def canonic_file_name(self, filem: FileMeta) -> Optional[str]:
        assert self.file_names is not None
        if self.name_template is None \
                and self.multifile is MultiFile.Disabled:
            return self.file_names[0]

        if self.name_template is not None:
            if Assignment._match_template(self.name_template,
                                          filem.shortname):
                return self.name_template

        for name in self.file_names:
            if Assignment._match_template(name, filem.shortname):
                return name
        return None

    def match(self, filem: FileMeta) -> bool:
        return self.canonic_file_name(filem) is not None

    @staticmethod
    def _match_template(raw_name_template: str, real_name: str) -> bool:
        name, ext = os.path.splitext(raw_name_template)
        return re.fullmatch(fr"(\d+-)?(\w+-)?{name}(_[a-z]+)?[.]{ext[1:]}",
                            real_name) is not None


class Config(common.BaseConfig):
    def __init__(self, raw: dict, args: Any) -> None:
        super().__init__(raw, args, "is")
        self.report_extra = raw.get("report_extra")

    def assignments(self, db: common.DBConnection) -> Iterable[Assignment]:
        asgns = self._assignments()
        return (Assignment(raw, name, self, db)
                for name, raw in asgns.items())


class EvaluationMode(enum.Enum):
    Ignored = enum.auto()
    Superseded = enum.auto()
    Submitted = enum.auto()

    @staticmethod
    def parse(raw: str) -> MultiFile:
        raw = raw[0].upper() + raw[1:].lower()
        return MultiFile.__members__[raw]

    def __str__(self) -> str:
        return self.name.lower()


@dataclass
class Submission:
    person_id: int
    timestamp: datetime
    files: Dict[str, FileMeta]
    dirty: bool
    asgn: Assignment
    superseded: List[FileMeta]

    def __init__(self, db: common.DBConnection, asgn: Assignment,
                 first_file: FileMeta) -> None:
        self.person_id = first_file.author
        self.timestamp = first_file.change_time
        name = asgn.canonic_file_name(first_file)
        assert name is not None
        self.files = {name: first_file}
        self.dirty = not file_processed(first_file, db)
        self.asgn = asgn
        self.superseded = []

    def add_file(self, db: common.DBConnection, filem: FileMeta) -> None:
        assert self.person_id == filem.author
        name = self.asgn.canonic_file_name(filem)
        assert name is not None

        new_name = name not in self.files
        new_version = not new_name and \
            self.files[name].change_time < filem.change_time
        if new_name or new_version:
            if new_version:
                self.superseded.append(self.files[name])
            self.timestamp = max(self.timestamp, filem.change_time)
            self.files[name] = filem
            self.dirty = self.dirty or not file_processed(filem, db)
        else:
            self.superseded.append(filem)

    def is_todo(self) -> bool:
        if self.asgn.multifile is not MultiFile.All:
            return self.dirty
        assert self.asgn.file_names is not None
        return self.dirty and len(self.files) == len(self.asgn.file_names)


def poll(args: argparse.Namespace, config: Config, db: common.DBConnection) \
        -> None:
    isconn = isapi.files.Connection()
    for asgn in config.assignments(db):
        if not asgn.enabled:
            continue
        if asgn.id is None:
            config.logger.info(f"Assignment {asgn.name} not in frag, skipping")
            continue

        config.logger.debug(f"Processing {asgn.name}…")
        assert asgn.file_names is not None
        if len(asgn.file_names) != 1 and asgn.multifile is MultiFile.Disabled:
            config.logger.warning(f"Assignment {asgn.name} has "
                                  f"{len(asgn.file_names)} files defined in "
                                  "frag, but it needs to have 1 "
                                  "(no multifile set). Skipping…")
            continue

        submissions, extra = collect_submissions(isconn, db, asgn)
        for sub in submissions:
            process_submission(config, db, isconn, sub)
        for filems in extra:
            process_extraneous(config, db, filems)


def process_extraneous(config: Config, db: common.DBConnection,
                       filems: List[FileMeta]) -> None:
    filems = [filem for filem in filems
              if not file_processed(filem, db,
                                    evaluated=EvaluationMode.Ignored)]
    if len(filems) == 0:
        return
    config.logger.warning(f"extra files for {filems[0].author}: {filems}")

    if config.report_extra:
        paths = [f'https://is.muni.cz/auth{filem.ispath}' for filem in filems]
        path_list = "    - " + "\n    - ".join(paths)

        author_uid = filems[0].author
        with db.cursor() as cur:
            cur.execute("select name from person where id = %s",
                        (author_uid,))
            row = cur.fetchone()
        author_name = row[0] if row else str(author_uid)

        subject = config.report_extra["subject"]
        text = config.report_extra["text"].format(path_list=path_list,
                                                  author=author_name)
        to = [to.format(uid=filems[0].author)
              for to in config.report_extra["to"]]

        msg = EmailMessage()
        msg.set_content(text)
        msg["Subject"] = subject
        msg["From"] = config.report_extra["from"]
        msg["To"] = ", ".join(to)
        with smtplib.SMTP('localhost') as smtp:
            smtp.send_message(msg)
    for filem in filems:
        confirm_file(filem, db, evaluated=EvaluationMode.Ignored)
    db.commit()


def collect_submissions(isconn: isapi.files.Connection,
                        db: common.DBConnection, asgn: Assignment) \
                        -> Tuple[List[Submission], List[List[FileMeta]]]:
    submissions: Dict[int, Submission] = {}
    unmatched: Dict[int, List[FileMeta]] = {}
    for ispath in asgn.sources:
        try:
            dirm = isconn.list_directory(ispath)
            for filem in dirm.entries:
                if asgn.match(filem):
                    db.logger.debug(f"found file {filem}")
                    if filem.author in submissions:
                        submissions[filem.author].add_file(db, filem)
                    else:
                        submissions[filem.author] = Submission(db, asgn, filem)
                else:
                    db.logger.debug(f"found unmatched {filem}")
                    unmatched.setdefault(filem.author, []).append(filem)
        except isapi.files.FileDoesNotExistException:
            db.logger.warning(f"Directory does not exist: {ispath}")

    return ([sub for sub in submissions.values() if sub.is_todo()],
            list(unmatched.values()))


def get_ispath_id(filem: FileMeta, cur: psycopg2.cursor) -> Optional[int]:
    cur.execute("select id from frag_ispoll.ispath where path = %s",
                (filem.ispath,))
    if cur.rowcount == 0:
        return None
    assert cur.rowcount == 1
    return typing.cast(int, cur.fetchone()[0])


def file_processed(filem: FileMeta, db: common.DBConnection,
                   evaluated: EvaluationMode = EvaluationMode.Superseded) \
                   -> bool:
    with db.cursor() as cur:
        ispath_id = get_ispath_id(filem, cur)
        if ispath_id is None:
            return False
        cur.execute("select count(*) from frag_ispoll.processed"
                    "  where ispath_id = %s"
                    "    and author = %s"
                    "    and change_time = %s"
                    "    and evaluated >= %s :: frag_ispoll.evaluation_mode",
                    (ispath_id, filem.author, to_utc_strip(filem.change_time),
                     str(evaluated)))
        return bool(cur.fetchone()[0])


def confirm_file(filem: FileMeta, db: common.DBConnection,
                 evaluated: EvaluationMode = EvaluationMode.Submitted) -> None:
    with db.cursor() as cur:
        cur.execute("insert into frag_ispoll.ispath (path)"
                    " values (%s)"
                    " on conflict do nothing"
                    " returning (id)",
                    (filem.ispath, ))
        res = cur.fetchone()
        ispath_id = res[0] if res is not None else get_ispath_id(filem, cur)
        assert ispath_id > 0
        cur.execute("insert into frag_ispoll.processed"
                    " (ispath_id, author, change_time, evaluated)"
                    " values (%s, %s, %s, %s :: frag_ispoll.evaluation_mode)"
                    " on conflict do nothing",
                    (ispath_id, filem.author, to_utc_strip(filem.change_time),
                     str(evaluated)))


def process_submission(config: Config, db: common.DBConnection,
                       isconn: isapi.files.Connection, sub: Submission) \
                       -> None:
    config.logger.info(f"processing {sub}…")
    assert sub.asgn.id is not None
    assert sub.asgn.file_names is not None
    common.submit_assignment(sub.asgn.id, sub.person_id, db,
                             [common.File(name,
                                          data=isconn.get_file(filem).data)
                              for name, filem in sub.files.items()],
                             sub.timestamp)

    for filem in sub.files.values():
        confirm_file(filem, db)
    # confirm also files superseded/shadowed by the submitted one
    for filem in sub.superseded:
        confirm_file(filem, db, evaluated=EvaluationMode.Superseded)
    db.commit()


def check_init_db(config: Config, db: common.DBConnection) -> None:
    common.create_schema_if_not_exists("frag_ispoll", db)
    with db.cursor() as cur:
        cur.execute("select count(*) from pg_catalog.pg_type"
                    "  where typname = 'evaluation_mode'")
        evaluation_mode_defined = bool(cur.fetchone()[0])
        if not evaluation_mode_defined:
            cur.execute("create type frag_ispoll.evaluation_mode as enum "
                        "  (%s, %s, %s)",
                        (str(EvaluationMode.Ignored),
                         str(EvaluationMode.Superseded),
                         str(EvaluationMode.Submitted)))

        cur.execute("create table if not exists frag_ispoll.ispath ("
                    "  id serial primary key,"
                    "  path bytea not null unique"
                    ")")
        cur.execute("""
            create table if not exists frag_ispoll.processed (
              ispath_id integer not null,
              change_time timestamp without time zone not null,
              author integer,
              evaluated frag_ispoll.evaluation_mode,
              timestamp timestamp without time zone default frag.utc_now_st(),
              constraint processed_ispath_id_ispath_id_fkey
                foreign key (ispath_id)
                  references frag_ispoll.ispath(id),
              constraint processed_unique
                unique (ispath_id, author, change_time, evaluated)
            )""")
        common.add_timestamp_to_processed(cur, "is")
        db.commit()


if __name__ == "__main__":
    common.main(cmdparser, Config, check_init_db, poll)

# vim: colorcolumn=80 expandtab sw=4 ts=4
